#ifndef SOFT_AP_PROVISION_TYPES_H
#define SOFT_AP_PROVISION_TYPES_H
#define SOFT_AP_PROVISION_TYPES_MAX_SSID_LEN 32
#define SOFT_AP_PROVISION_TYPES_MAX_PASS_LEN 64
typedef struct {
    char ssid[SOFT_AP_PROVISION_TYPES_MAX_SSID_LEN];
    char password[SOFT_AP_PROVISION_TYPES_MAX_PASS_LEN];
} wifi_credentials_t;
#endif // !SOFT_AP_PROVISION_TYPES_H
